import os

import gradio as gr

from rag import answer_question


def chat(message: str, history: list[dict]) -> str:
    """Answer one question using the paper as the only knowledge source."""
    del history  # The naive RAG prompt intentionally answers each turn independently.
    try:
        return answer_question(message)
    except Exception as error:
        return f"Unable to answer the question: {error}"


demo = gr.ChatInterface(
    fn=chat,
    chatbot=gr.Chatbot(height=560),
    textbox=gr.Textbox(
        placeholder="Ask a question about the lung cancer detection paper...",
        container=False,
        scale=7,
        submit_btn="Ask",
        stop_btn="Stop",
    ),
    title="RAG Paper Assistant",
    description=(
        "Ask questions about the research paper. Answers are generated by Gemini "
        "through OpenRouter using retrieved paper excerpts."
    ),
    examples=[
        "What accuracy did VGG16 achieve?",
        "Which model had the highest training accuracy?",
        "Why was MobileNetV2 useful for resource-constrained environments?",
    ],
)


if __name__ == "__main__":
    demo.launch(
        server_name=os.getenv("GRADIO_SERVER_NAME", "127.0.0.1"),
        server_port=int(os.getenv("GRADIO_SERVER_PORT", "7860")),
    )
